#!/bin/bash

HTML_SERVER_NAME=html.localhost
PHP_SERVER_NAME=php.localhost

################################
# Setup a HTML static web site #
################################

# Install nginx http server
sudo apt-get install nginx

su

cat > /etc/nginx/sites-available/default << "EOF"
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
        listen 80;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

}
EOF

# Set a new hostname for the html static virutal host
sudo sed -i "s/server_name _;/server_name $HTML_SERVER_NAME;/" /etc/nginx/sites-available/default 

# Starts the service
sudo systemctl enable nginx


##########################
# set a php powered site #
##########################

sudo apt-get install php5 php5-fpm

sudo mkdir /var/www/php

su

cat > /etc/nginx/sites-available/test-php << EOF
server {
    listen 80;
    server_name $PHP_SERVER_NAME;
    root /var/www/php;
    index index.php index.html index.htm;

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass  unix:/run/php5-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param QUERY_STRING    $query_string;
    }

    location ~* \.(js|css)$ {
        expires 1h;
    }

    location ~* \.(eot|otf|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
    }
}
EOF

cat > /var/www/php/index.php << "EOF"
<html>
 <head>
  <title>Hello from PHP</title>
 </head>
 <body>
 <?php phpinfo(); ?> 
 </body>
</html>
EOF

ln -sf /etc/nginx/sites-available/test-php /etc/nginx/sites-enabled/test-php

sudo systemctl enable php5-fpm
sudo systemctl reload nginx

echo "html static server is reachable with hostname $HTML_SERVER_NAME"
echo "PHP server is reachable with hostname $PHP_SERVER_NAME"
echo "Don't forget to add these hostname at IP $(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}') to you hosts file if you want to test it in your network with another computer"
